# Generated by Django 5.1.6 on 2025-04-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_path',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
